# Generated by Django 5.0.2 on 2024-02-27 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemonAPI', '0002_drinks_menuitem_drinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='drinks',
            field=models.ForeignKey(default='juce', on_delete=django.db.models.deletion.PROTECT, to='lemonAPI.drinks'),
        ),
    ]
