# Generated by Django 5.0.2 on 2024-02-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemonAPI', '0005_alter_menuitem_drinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='drinks',
        ),
    ]
