# Generated by Django 5.0.2 on 2024-02-27 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemonAPI', '0007_menuitem_drinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinks',
            name='price',
        ),
        migrations.AddField(
            model_name='drinks',
            name='slug',
            field=models.SlugField(default=99),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='drinks',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lemonAPI.drinks'),
        ),
    ]
