# Generated by Django 5.0.2 on 2024-02-27 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemonAPI', '0008_remove_drinks_price_drinks_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='drinks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lemonAPI.drinks'),
        ),
    ]
