# Generated by Django 5.0.2 on 2024-02-27 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemonAPI', '0010_alter_menuitem_drinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='drinks',
        ),
        migrations.DeleteModel(
            name='Drinks',
        ),
    ]
