# Generated by Django 5.0.2 on 2024-02-27 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemonAPI', '0011_remove_menuitem_drinks_delete_drinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='drinks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lemonAPI.category'),
        ),
    ]
