# Generated by Django 5.0.2 on 2024-02-27 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemonAPI', '0012_category_menuitem_drinks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Drinks',
        ),
    ]
