# Generated by Django 5.0.2 on 2024-02-27 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemonAPI', '0013_rename_category_drinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='drinks',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lemonAPI.drinks'),
        ),
    ]
