# Generated by Django 5.0.2 on 2024-03-01 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemonAPI', '0014_alter_menuitem_drinks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drinks',
            new_name='Category',
        ),
    ]
