# Generated by Django 5.0.2 on 2024-03-01 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemonAPI', '0015_rename_drinks_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='drinks',
            new_name='category',
        ),
    ]
